### ISSUE TITLE
About the mod ...

### ISSUE THREAD

**Issue by ghost** [Team-RTG/Passable-Leaves#15]
Just some questions about the mod : 
- how did you get the idea to make it?
- do you plan to not use ASM?
- did you used a part of my code to make it (you know, TheRealisticLeavesMod)?
- could you add quicksands and passable snow (I had the idea to add that to my mod before)?
Thanks.

**Comment by srs-bsns** [comment]
>how did you get the idea to make it?

This was originally a part of [Team-RTG/Appalachia](https://github.com/Team-RTG/Appalachia), which is an unreleased add-on for [Team-RTG/Realistic-Terrain-Generation](https://github.com/Team-RTG/Realistic-Terrain-Generation). It was felt that, due to changing core Minecraft classes, it was best to separate the coremod into it's own mod. This decision was made so that RTG, or it's add-ons, did not contain a core mod, and also to make maintaining it much easier.

>do you plan to not use ASM?

It is impossible to achieve what this mod does without altering the `net.minecraft.block.BlockLeaves` base class. So, no.

>did you used a part of my code to make it (you know, TheRealisticLeavesMod)?

All of our code is written from scratch. No one even knew about the existence of your mod. (Besides, your mod is for 1.7.10 only and your source is not available.)

>could you add quicksands and passable snow (I had the idea to add that to my mod before)?

No. Changing anything else would be outside of the scope of what this coremod does. It's purpose is simply to make it so that entities can move through leaf blocks, nothing more.
