### ISSUE TITLE
A Small But Important Request/Improvement

### ISSUE THREAD

**Issue by ghost** [Team-RTG/Passable-Leaves#18]
can you add passability for snow layer x1 to avoid this please?
![2018-06-22_17 31 17](https://user-images.githubusercontent.com/24831406/41782188-38513b0c-7642-11e8-916d-cdc2332d8874.png)
thanks.

**Comment by srs-bsns** [comment]
Such a change is outside the scope of this mod. This mod only exists to alter leaves, hence the name Passable **Leaves**.

In order to alter snow layers it would require expanding upon the coremod (undesirable) to add a class transformer for `BlockSnow`. The handing of collisions with the modified snow layers would be more complex than with leaves because of the existing collision handling which is dependant on how many layers are present.

**Comment by ghost** [comment]
well... the main issue is i can't pass **leaves** cus of the snow blocks... it should be an issue with Passable **Leaves**
but ok... as you wish

**Comment by ghost** [comment]
Would really love to see a resolution for this!
