### ISSUE TITLE
Cannot pass through Cuisine and Natural Pledge leaves

### ISSUE THREAD

**Issue by breadguyyy** [Team-RTG/Passable-Leaves#21]
For whatever reason, the leaves from the Natural Pledge trees and Cuisine fruit trees are still solid. No issues with any other modded leaves. Thank you for the mod!

**Comment by srs-bsns** [comment]
Neither of the leaf blocks from those mods are decendents of Minecraft's leaf block class (`BlockLeaves`), therefore this mod will have no effect on them. This is an issue with those mods, not Passable Leaves. Mods creating custom leaf blocks should always extend the vanilla `BlockLeaves` class.

**Comment by breadguyyy** [comment]
opening this back up again because i talked to the cuisine mod author and they said they said: "No, this is issue with Passable Leaves. There is no need to extend vanilla BlockLeaves class. Implementing isLeaves is a way as well. In view of the particularity of our leaves we decide not to extend vanilla class. If they cannot come up with a good solution, we can consider to add a compatibility feature." if this isnt the case ill talk to them about some sort of compat

**Comment by srs-bsns** [comment]
There is no manner in which this mod will work with others unless their leaf blocks are decenents of `BlockLeaves`. PassableLeaves works by making byte code level changes to `BlockLeaves`, and although those changes __could__ technically also be applied to other mods classes, this will never be done as it is considered a gross violation of good community etiquette. It's already disparaged to even make such changes to vanilla classes, but this is the only way that the original authors thought would work to make impassible blocks passable.

If it is a mod author's prerogative to not subclass `BlockLeaves` for whatever reason, (I'm guessing in most cases it would be due to subclassing their own custom base block instead of a vanilla one, in which case the issue is with Java being single-inheritance), then it will just have to be accepted that that mod and PassableLeaves are not compatible.

Due to the changes made in both Minecraft and Forge in 1.13 and to the mechanics of how a blocks passability is handled, this mod would basically need a full rewrite from scratch (and will not likely require the current byte code changes), and due to that and limited time, PassableLeaves in it's current state, will not be receiving any more updates for 1.12 and prior.

**Comment by breadguyyy** [comment]
okay thank you for looking into it!
