### ISSUE TITLE
Jungle Leaves

### ISSUE THREAD

**Issue by Noviian** [Team-RTG/Passable-Leaves#22]
I'm not sure if this is just supposed to be the passive difficulty that comes with having passable leaves, but I found jungle biomes absolutely impossible to traverse without either making myself a very block-expensive bridge to anywhere I want to explore, or hacking my way through leaves with shears.

A few solutions I've thought of:
-making jungle leaves an exception to the passable leaves, marking them off as just really dense forestry, 
     which I feel like what a jungle is supposed to be. Even allowing you to configure whether or 
     not to allow or disallow certain types of leaves would be awesome.
-some sort of enchantment, armour piece, or item that allows you to walk over leaves. Think of 
     snowshoes for walking over snow, distributing the weight. Or maybe just a "nimble" enchantment to 
     put on shoes or something.
-allowing swords to cut through leaves like shears. This is the less favourable solution in my opinion as 
     I'd still have to go through all the work of cutting the leaves to walk around, but at least I wouldn't 
     have to carry shears around.

I may sound kind of ignorant as I don't know the limits or difficulties of programming but as of right now I'm leaning towards just disabling the mod for my current playthrough even though I like the idea of falling through leaves.
_I'm not even completely sure if you're still active here or not_

**Comment by srs-bsns** [comment]
> -making jungle leaves an exception to the passable leaves

Passable Leaves works by modifying the base block class for leaves for which the functionality is adopted through inheritence. Jungle leaves can not be opted out of this without it being overly convoluted and complicated.

> -some sort of enchantment, armour piece, or item that allows you to walk over leaves.

The objective of this mod is to alter basic game behaviour. Adding objects to the game is outside of it's scope.

> -allowing swords to cut through leaves like shears.

Modifying the bahaviour of swords would also fall outside of the scope of this mod.

---
Honestly, jungles are meant to be dense and difficult to move through. With Passable Leaves you can't unrealistically move across the top of leaves like you can in vanilla, but you can move through them with a speed reduction which is far more like reality. If you feel that you are moving too slow through them, you can always alter the speed reduction settings so that leaves will slow you down less.
