### ISSUE TITLE
[Suggestion] being able to add our own block (reupload)

### ISSUE THREAD

**Issue by Zack7292** [Team-RTG/Passable-Leaves#27]
Hey, i'll like to be able to add my own block of leaves that you can pass through, bcs since its not compatible with Biome You'll Go, i'll like to add his leaves. !!! I'll like this to be add so we can add Mcreator's leaves !!!

**Comment by MoeBoy76** [comment]
This will not happen, it’s completely outside the scope of the mod, to fix this is a simple change by the leaf block adding mod

**Comment by srs-bsns** [comment]
Adding the ability to add custom blocks would basically require a rewrite of how this mod works.
This mod will not be updated beyond 1.12 due to several limitations in how it works.
This mod will no longer be updated for 1.12 as it has reached it's EOL as per: https://www.minecraftforge.net/forum/topic/79304-112114-and-lts-system/

For the future (1.14 and beyond), I have written another mod (currently unreleased) that will replace this mod and not have its deficiencies: [srsCode/FallThru](https://github.com/srsCode/FallThru)
